nav:
  - Home: index.md
  - About:
    - About Python: 0-about/python.md
    - About LlamaIndex: 0-about/llamaindex.md
  - Setup:
    - Visual Code Setup: 0-setup/0.1-visual-studio-code-setup.md
    - Project Basic Setup: 0-setup/0.2-project-basic-setup.md
    - Install Packages: 0-setup/0.3-install-packages.md
    - Before Run Project: 0-setup/0.4-before-run.md
    - Run Project: 0-setup/0.5-run-project.md
  - Tutorial: 
    - LlamaParse: 1-tutorial/1.1-tutorial-parse.md
theme:
  name: readthedocs
#For Local : Set use_directory_urls to false and site_name "". Otherwise, internal links between pages will not work properly.
site_name: ""
use_directory_urls: false